using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CuberLib;

namespace Cuber
{
    class Program
    {
		// Note: This will probably only work well with OBJ files generated by Pix4D
		// as I have only supported the subset of data types it outputs.
		static void Main(string[] args)
        {
			if (args.Length < 1)
			{
				Console.WriteLine("Please provide the path to a .obj file");
				return;
			};
			
			string path = args[0];

			// Parse and load the object
			Console.WriteLine("Loading {0}", path);
            Obj obj = new Obj();
			obj.LoadObj(path, ShowLinesLoaded);

			// Write out a bit of info about the object
			Console.WriteLine("Loaded {0} vertices and {1} faces", obj.VertexList.Count(), obj.FaceList.Count());
			Console.WriteLine("Size: X {0} Y {1} Z {2}", obj.Size.XSize, obj.Size.YSize, obj.Size.ZSize);
			Console.WriteLine("Memory Used: " + GC.GetTotalMemory(true) / 1024 / 1024 + "mb");

			// Generate some tiles, we are ignoring Z all the way through the 
			// stack right now.  In our OBJ files Z is a vector towards the center of the earth.
			for (int x = 0; x < 20; x++)
			{
				for (int y = 0; y < 20; y++)
				{
					for (int z = 0; z < 2; z++)
					{
						obj.WriteObjGridTile(string.Format("H:\\aerialdata\\tiling_justin\\output_{0}_{1}_{2}.obj", x, y, z), 40, 40, 3, x, y, z);
					}
				}
			}

			Console.WriteLine("Complete");
            Console.ReadKey();
        }

		// Action to show incremental file loading status
        public static void ShowLinesLoaded(int lines)
        {
            Console.SetCursorPosition(0, 10);
            Console.Write("Loaded {0} lines             ", lines);
            Console.SetCursorPosition(0, 0);
        }
    }
}
